package main

func main() {
	// pointers()
	// structs()
	// structFields()
	// pointersToStructs()
	// structLiterals()
	// arrays()
	// slices()
	// sliceAreLikeReferencesToArrays()
	// sliceLiterals()
	// sliceDefaults()
	//sliceLengthCapacity()
	// nilSlice()
	// creatingASliceWithMake()
	// sliceOfSlice()
	// appendingToASlice()
	// rangeSample()
	// mapSample()
	// mutatingMap()
	// execiseMap()
	// fucntionValues()
	// functionClosure()
	// execiseFibonacciClosure()
	// method()
	// methodsContinued()
	// pointerRecivers()
	// methodsAndPointerIndirection()
	// methodsAndPointerIndirection2()
	// interfaces()
	// interfaceValues()
	// interfaceValuesWithNilUnderlyigValues()
	// nilInterfaceValues()
	// typeAssertions()
	// typeSwitches()
	exerciseStringer()
}